@startuml

    class Asset [[Asset.html]] {
        +getCommodity(): Commodity
        +getListedProduct(): ListedProduct
        +toBuilder(): Asset.AssetBuilder
        {static} +builder(): Asset.AssetBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
