@startuml

    class AutomaticExercise.AutomaticExerciseBuilder [[AutomaticExercise.AutomaticExerciseBuilder.html]] {
        +getThresholdRate(): BigDecimal
        +setThresholdRate(BigDecimal): AutomaticExercise.AutomaticExerciseBuilder
        +build(): AutomaticExercise
    }

@enduml
