@startuml

    class BrokerConfirmation.BrokerConfirmationBuilder [[BrokerConfirmation.BrokerConfirmationBuilder.html]] {
        +getBrokerConfirmationType(): BrokerConfirmationTypeEnum
        +getBrokerConfirmationTypeScheme(): String
        +setBrokerConfirmationType(BrokerConfirmationTypeEnum): BrokerConfirmation.BrokerConfirmationBuilder
        +setBrokerConfirmationTypeScheme(String): BrokerConfirmation.BrokerConfirmationBuilder
        +build(): BrokerConfirmation
    }

@enduml
