@startuml

    class CalculationPeriodFrequency [[CalculationPeriodFrequency.html]] {
        +getRollConvention(): RollConventionEnum
        +toBuilder(): CalculationPeriodFrequency.CalculationPeriodFrequencyBuilder
        {static} +builder(): CalculationPeriodFrequency.CalculationPeriodFrequencyBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
