@startuml

    enum ContractualDefinitionsEnum [[ContractualDefinitionsEnum.html]] {
        {static} +ISDA1991
        {static} +ISDA_1993_COMMODITY
        {static} +ISDA_1996_EQUITY
        {static} +ISDA_1997_BULLION
        {static} +ISDA_1997_GOVERNMENT_BOND
        {static} +ISDA1998FX
        {static} +ISDA_1999_CREDIT
        {static} +ISDA2000
        {static} +ISDA_2002_EQUITY
        {static} +ISDA_2003_CREDIT
        {static} +ISDA_2004_NOVATION
        {static} +ISDA_2005_COMMODITY
        {static} +ISDA2006
        {static} +ISDA_2006_INFLATION
        {static} +ISDA_2008_INFLATION
        {static} +ISDA_2011_EQUITY
        {static} +ISDA_2014_CREDIT
    }

@enduml
