@startuml

    class ContractIdentifierExtended.ContractIdentifierExtendedBuilder [[ContractIdentifierExtended.ContractIdentifierExtendedBuilder.html]] {
        +getAssociatedParty(): String
        +setAssociatedParty(String): ContractIdentifierExtended.ContractIdentifierExtendedBuilder
        +build(): ContractIdentifierExtended
    }

@enduml
