@startuml

    class CrossCurrencyMethod [[CrossCurrencyMethod.html]] {
        +getCashSettlementCurrency(): List<String>
        +getCashSettlementCurrencyScheme(): String
        +getCashSettlementReferenceBanks(): List<CashSettlementReferenceBanks>
        +getQuotationRateType(): QuotationRateTypeEnum
        +toBuilder(): CrossCurrencyMethod.CrossCurrencyMethodBuilder
        {static} +builder(): CrossCurrencyMethod.CrossCurrencyMethodBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
