@startuml

    class DateRelativeToPaymentDates.DateRelativeToPaymentDatesBuilder [[DateRelativeToPaymentDates.DateRelativeToPaymentDatesBuilder.html]] {
        +getPaymentDatesReference(): List<String>
        +addPaymentDatesReference(String): DateRelativeToPaymentDates.DateRelativeToPaymentDatesBuilder
        +build(): DateRelativeToPaymentDates
    }

@enduml
