@startuml

    class DateRelativeToCalculationPeriodDates.DateRelativeToCalculationPeriodDatesBuilder [[DateRelativeToCalculationPeriodDates.DateRelativeToCalculationPeriodDatesBuilder.html]] {
        +getCalculationPeriodDatesReference(): List<String>
        +addCalculationPeriodDatesReference(String): DateRelativeToCalculationPeriodDates.DateRelativeToCalculationPeriodDatesBuilder
        +build(): DateRelativeToCalculationPeriodDates
    }

@enduml
