@startuml

    enum DayOfWeekEnum [[DayOfWeekEnum.html]] {
        {static} +MON
        {static} +TUE
        {static} +WED
        {static} +THU
        {static} +FRI
        {static} +SAT
        {static} +SUN
    }

@enduml
