@startuml

    enum EntityTypeEnum [[EntityTypeEnum.html]] {
        {static} +ASIAN
        {static} +AUSTRALIAN_AND_NEW_ZEALAND
        {static} +EUROPEAN_EMERGING_MARKETS
        {static} +JAPANESE
        {static} +NORTH_AMERICAN_HIGH_YIELD
        {static} +NORTH_AMERICAN_INSURANCE
        {static} +NORTH_AMERICAN_INVESTMENT_GRADE
        {static} +SINGAPOREAN
        {static} +WESTERN_EUROPEAN
        {static} +WESTERN_EUROPEAN_INSURANCE
    }

@enduml
