@startuml

    class Execution [[Execution.html]] {
        +getContractualProduct(): ContractualProduct
        +getParty(): List<Party>
        +getTradeHeader(): TradeHeader
        +toBuilder(): Execution.ExecutionBuilder
        {static} +builder(): Execution.ExecutionBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
