@startuml

    class ExerciseFee [[ExerciseFee.html]] {
        +getFeeAmount(): BigDecimal
        +getFeePaymentDate(): RelativeDateOffset
        +getFeeRate(): BigDecimal
        +getNotionalReference(): String
        +toBuilder(): ExerciseFee.ExerciseFeeBuilder
        {static} +builder(): ExerciseFee.ExerciseFeeBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
