@startuml

    class FailureToPay [[FailureToPay.html]] {
        +getApplicable(): Boolean
        +getGracePeriodExtension(): GracePeriodExtension
        +getPaymentRequirement(): Money
        +toBuilder(): FailureToPay.FailureToPayBuilder
        {static} +builder(): FailureToPay.FailureToPayBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
