@startuml

    class GrossCashflow [[GrossCashflow.html]] {
        +getCashflowAmount(): Money
        +getCashflowCalculation(): String
        +getCashflowType(): CashflowTypeEnum
        +getPayoutLineage(): PayoutLineage
        +toBuilder(): GrossCashflow.GrossCashflowBuilder
        {static} +builder(): GrossCashflow.GrossCashflowBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
