@startuml

    class LoanParticipation.LoanParticipationBuilder [[LoanParticipation.LoanParticipationBuilder.html]] {
        +getQualifyingParticipationSeller(): String
        +setQualifyingParticipationSeller(String): LoanParticipation.LoanParticipationBuilder
        +build(): LoanParticipation
    }

@enduml
