@startuml

    class Money [[Money.html]] {
        +getAmount(): BigDecimal
        +getCurrency(): String
        +getCurrencyScheme(): String
        +getId(): String
        +toBuilder(): Money.MoneyBuilder
        {static} +builder(): Money.MoneyBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
