@startuml

    class NaturalPersonRole.NaturalPersonRoleBuilder [[NaturalPersonRole.NaturalPersonRoleBuilder.html]] {
        +getPersonReference(): String
        +getRole(): NaturalPersonRoleEnum
        +getRoleScheme(): String
        +setPersonReference(String): NaturalPersonRole.NaturalPersonRoleBuilder
        +setRole(NaturalPersonRoleEnum): NaturalPersonRole.NaturalPersonRoleBuilder
        +setRoleScheme(String): NaturalPersonRole.NaturalPersonRoleBuilder
        +build(): NaturalPersonRole
    }

@enduml
