@startuml

    class PartyContractInformation [[PartyContractInformation.html]] {
        +getNaturalPersonRole(): List<NaturalPersonRole>
        +getPartyReference(): String
        +toBuilder(): PartyContractInformation.PartyContractInformationBuilder
        {static} +builder(): PartyContractInformation.PartyContractInformationBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
