@startuml

    class PaymentRule [[PaymentRule.html]] {
        +getPercentageRule(): PercentageRule
        +toBuilder(): PaymentRule.PaymentRuleBuilder
        {static} +builder(): PaymentRule.PaymentRuleBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
