@startuml

    class ProductTaxonomy [[ProductTaxonomy.html]] {
        +getTaxonomySource(): TaxonomySourceEnum
        +getTaxonomyValue(): String
        +toBuilder(): ProductTaxonomy.ProductTaxonomyBuilder
        {static} +builder(): ProductTaxonomy.ProductTaxonomyBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
