@startuml

    class ResourceLength [[ResourceLength.html]] {
        +getLengthUnit(): LengthUnitEnum
        +getLengthValue(): BigDecimal
        +toBuilder(): ResourceLength.ResourceLengthBuilder
        {static} +builder(): ResourceLength.ResourceLengthBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
