@startuml

    class TermsChangePrimitive [[TermsChangePrimitive.html]] {
        +getAfter(): ContractOrContractReference
        +getBefore(): ContractOrContractReference
        +toBuilder(): TermsChangePrimitive.TermsChangePrimitiveBuilder
        {static} +builder(): TermsChangePrimitive.TermsChangePrimitiveBuilder
        #rosettaKeyValueHashCode(): int
    }

@enduml
