@startuml

    class AdjustedRelativeDateOffsetValidator [[AdjustedRelativeDateOffsetValidator.html]] {
        +validate(AdjustedRelativeDateOffset): ValidationResult<AdjustedRelativeDateOffset>
    }

@enduml
