@startuml

    class AdjustableOrRelativeDatesValidator [[AdjustableOrRelativeDatesValidator.html]] {
        +validate(AdjustableOrRelativeDates): ValidationResult<AdjustableOrRelativeDates>
    }

@enduml
