@startuml

    class AdjustableOrAdjustedDateValidator [[AdjustableOrAdjustedDateValidator.html]] {
        +validate(AdjustableOrAdjustedDate): ValidationResult<AdjustableOrAdjustedDate>
    }

@enduml
