@startuml

    class AdjustableOrRelativeDateValidator [[AdjustableOrRelativeDateValidator.html]] {
        +validate(AdjustableOrRelativeDate): ValidationResult<AdjustableOrRelativeDate>
    }

@enduml
