@startuml

    class AveragingObservationListValidator [[AveragingObservationListValidator.html]] {
        +validate(AveragingObservationList): ValidationResult<AveragingObservationList>
    }

@enduml
