@startuml

    class BasketReferenceInformationValidator [[BasketReferenceInformationValidator.html]] {
        +validate(BasketReferenceInformation): ValidationResult<BasketReferenceInformation>
    }

@enduml
