@startuml

    class CalculationPeriodFrequencyValidator [[CalculationPeriodFrequencyValidator.html]] {
        +validate(CalculationPeriodFrequency): ValidationResult<CalculationPeriodFrequency>
    }

@enduml
