@startuml

    class CancelableProvisionAdjustedDatesValidator [[CancelableProvisionAdjustedDatesValidator.html]] {
        +validate(CancelableProvisionAdjustedDates): ValidationResult<CancelableProvisionAdjustedDates>
    }

@enduml
