@startuml

    class CashSettlementPaymentDateValidator [[CashSettlementPaymentDateValidator.html]] {
        +validate(CashSettlementPaymentDate): ValidationResult<CashSettlementPaymentDate>
    }

@enduml
