@startuml

    class CashSettlementReferenceBanksValidator [[CashSettlementReferenceBanksValidator.html]] {
        +validate(CashSettlementReferenceBanks): ValidationResult<CashSettlementReferenceBanks>
    }

@enduml
