@startuml

    class ContractualTermsSupplementValidator [[ContractualTermsSupplementValidator.html]] {
        +validate(ContractualTermsSupplement): ValidationResult<ContractualTermsSupplement>
    }

@enduml
