@startuml

    class ContractIdentifierExtendedValidator [[ContractIdentifierExtendedValidator.html]] {
        +validate(ContractIdentifierExtended): ValidationResult<ContractIdentifierExtended>
    }

@enduml
