@startuml

    class ContractOrContractReferenceValidator [[ContractOrContractReferenceValidator.html]] {
        +validate(ContractOrContractReference): ValidationResult<ContractOrContractReference>
    }

@enduml
