@startuml

    class DateRelativeToPaymentDatesValidator [[DateRelativeToPaymentDatesValidator.html]] {
        +validate(DateRelativeToPaymentDates): ValidationResult<DateRelativeToPaymentDates>
    }

@enduml
