@startuml

    class DateRelativeToCalculationPeriodDatesValidator [[DateRelativeToCalculationPeriodDatesValidator.html]] {
        +validate(DateRelativeToCalculationPeriodDates): ValidationResult<DateRelativeToCalculationPeriodDates>
    }

@enduml
