@startuml

    class ExtendibleProvisionAdjustedDatesValidator [[ExtendibleProvisionAdjustedDatesValidator.html]] {
        +validate(ExtendibleProvisionAdjustedDates): ValidationResult<ExtendibleProvisionAdjustedDates>
    }

@enduml
