@startuml

    class FinalCalculationPeriodDateAdjustmentValidator [[FinalCalculationPeriodDateAdjustmentValidator.html]] {
        +validate(FinalCalculationPeriodDateAdjustment): ValidationResult<FinalCalculationPeriodDateAdjustment>
    }

@enduml
