@startuml

    class FloatingAmountProvisionsValidator [[FloatingAmountProvisionsValidator.html]] {
        +validate(FloatingAmountProvisions): ValidationResult<FloatingAmountProvisions>
    }

@enduml
