@startuml

    class FxLinkedNotionalScheduleValidator [[FxLinkedNotionalScheduleValidator.html]] {
        +validate(FxLinkedNotionalSchedule): ValidationResult<FxLinkedNotionalSchedule>
    }

@enduml
