@startuml

    class IndexReferenceInformationValidator [[IndexReferenceInformationValidator.html]] {
        +validate(IndexReferenceInformation): ValidationResult<IndexReferenceInformation>
    }

@enduml
