@startuml

    class InflationRateCalculationValidator [[InflationRateCalculationValidator.html]] {
        +validate(InflationRateCalculation): ValidationResult<InflationRateCalculation>
    }

@enduml
