@startuml

    class MandatoryEarlyTerminationValidator [[MandatoryEarlyTerminationValidator.html]] {
        +validate(MandatoryEarlyTermination): ValidationResult<MandatoryEarlyTermination>
    }

@enduml
