@startuml

    class MandatoryEarlyTerminationAdjustedDatesValidator [[MandatoryEarlyTerminationAdjustedDatesValidator.html]] {
        +validate(MandatoryEarlyTerminationAdjustedDates): ValidationResult<MandatoryEarlyTerminationAdjustedDates>
    }

@enduml
