@startuml

    class NonDeliverableSettlementValidator [[NonDeliverableSettlementValidator.html]] {
        +validate(NonDeliverableSettlement): ValidationResult<NonDeliverableSettlement>
    }

@enduml
