@startuml

    class NonNegativeAmountScheduleValidator [[NonNegativeAmountScheduleValidator.html]] {
        +validate(NonNegativeAmountSchedule): ValidationResult<NonNegativeAmountSchedule>
    }

@enduml
