@startuml

    class OptionalEarlyTerminationValidator [[OptionalEarlyTerminationValidator.html]] {
        +validate(OptionalEarlyTermination): ValidationResult<OptionalEarlyTermination>
    }

@enduml
