@startuml

    class OptionalEarlyTerminationAdjustedDatesValidator [[OptionalEarlyTerminationAdjustedDatesValidator.html]] {
        +validate(OptionalEarlyTerminationAdjustedDates): ValidationResult<OptionalEarlyTerminationAdjustedDates>
    }

@enduml
