@startuml

    class OptionPhysicalSettlementValidator [[OptionPhysicalSettlementValidator.html]] {
        +validate(OptionPhysicalSettlement): ValidationResult<OptionPhysicalSettlement>
    }

@enduml
