@startuml

    class PartyAndAccountReferenceValidator [[PartyAndAccountReferenceValidator.html]] {
        +validate(PartyAndAccountReference): ValidationResult<PartyAndAccountReference>
    }

@enduml
