@startuml

    class PartyContractInformationValidator [[PartyContractInformationValidator.html]] {
        +validate(PartyContractInformation): ValidationResult<PartyContractInformation>
    }

@enduml
