@startuml

    class PaymentCalculationPeriodValidator [[PaymentCalculationPeriodValidator.html]] {
        +validate(PaymentCalculationPeriod): ValidationResult<PaymentCalculationPeriod>
    }

@enduml
