@startuml

    class PCDeliverableObligationCharacValidator [[PCDeliverableObligationCharacValidator.html]] {
        +validate(PCDeliverableObligationCharac): ValidationResult<PCDeliverableObligationCharac>
    }

@enduml
