@startuml

    class PhysicalSettlementPeriodValidator [[PhysicalSettlementPeriodValidator.html]] {
        +validate(PhysicalSettlementPeriod): ValidationResult<PhysicalSettlementPeriod>
    }

@enduml
