@startuml

    class PubliclyAvailableInformationValidator [[PubliclyAvailableInformationValidator.html]] {
        +validate(PubliclyAvailableInformation): ValidationResult<PubliclyAvailableInformation>
    }

@enduml
