@startuml

    class StubCalculationPeriodAmountValidator [[StubCalculationPeriodAmountValidator.html]] {
        +validate(StubCalculationPeriodAmount): ValidationResult<StubCalculationPeriodAmount>
    }

@enduml
