@startuml

    class WeightedAveragingObservationValidator [[WeightedAveragingObservationValidator.html]] {
        +validate(WeightedAveragingObservation): ValidationResult<WeightedAveragingObservation>
    }

@enduml
