@startuml

    class AdjustableOrAdjustedDateAdjustedDateDataRule [[AdjustableOrAdjustedDateAdjustedDateDataRule.html]] {
        +validate(AdjustableOrAdjustedDate): ValidationResult<AdjustableOrAdjustedDate>
    }

@enduml
