@startuml

    class AdjustableOrAdjustedOrRelativeDateAdjustedDateDataRule [[AdjustableOrAdjustedOrRelativeDateAdjustedDateDataRule.html]] {
        +validate(AdjustableOrAdjustedOrRelativeDate): ValidationResult<AdjustableOrAdjustedOrRelativeDate>
    }

@enduml
