@startuml

    class BasketReferenceInformationNthToDefaultDataRule [[BasketReferenceInformationNthToDefaultDataRule.html]] {
        +validate(BasketReferenceInformation): ValidationResult<BasketReferenceInformation>
    }

@enduml
