@startuml

    class CalculationPeriodDatesCalculationPeriodDatesAdjustmentsDataRule [[CalculationPeriodDatesCalculationPeriodDatesAdjustmentsDataRule.html]] {
        +validate(Payout): ValidationResult<Payout>
    }

@enduml
