@startuml

    class CalculationPeriodDatesFirstCompoundingPeriodEndDateDataRule [[CalculationPeriodDatesFirstCompoundingPeriodEndDateDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
