@startuml

    class CalculationPeriodDatesCalculationPeriodFrequencyDataRule [[CalculationPeriodDatesCalculationPeriodFrequencyDataRule.html]] {
        +validate(Payout): ValidationResult<Payout>
    }

@enduml
