@startuml

    class CalculationPeriodCalculationPeriodNumberOfDaysDataRule [[CalculationPeriodCalculationPeriodNumberOfDaysDataRule.html]] {
        +validate(PaymentCalculationPeriod): ValidationResult<PaymentCalculationPeriod>
    }

@enduml
