@startuml

    class CashSettlementTermsRecoveryFactorDataRule [[CashSettlementTermsRecoveryFactorDataRule.html]] {
        +validate(CashSettlementTerms): ValidationResult<CashSettlementTerms>
    }

@enduml
