@startuml

    class CashSettlementTermsCashSettlementBusinessDaysDataRule [[CashSettlementTermsCashSettlementBusinessDaysDataRule.html]] {
        +validate(CashSettlementTerms): ValidationResult<CashSettlementTerms>
    }

@enduml
