@startuml

    class ConstituentWeightBasketPercentageDataRule [[ConstituentWeightBasketPercentageDataRule.html]] {
        +validate(ConstituentWeight): ValidationResult<ConstituentWeight>
    }

@enduml
