@startuml

    class DeliverableObligationsPhysicalSettlementMatrixDataRule [[DeliverableObligationsPhysicalSettlementMatrixDataRule.html]] {
        +validate(Contract): ValidationResult<Contract>
    }

@enduml
