@startuml

    class EarlyTerminationProvisionMandatoryEarlyTerminationDataRule [[EarlyTerminationProvisionMandatoryEarlyTerminationDataRule.html]] {
        +validate(EarlyTerminationProvision): ValidationResult<EarlyTerminationProvision>
    }

@enduml
