@startuml

    class FinalStubLastRegularPaymentDateDataRule [[FinalStubLastRegularPaymentDateDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
