@startuml

    class FirstRegularPeriodStartDateInitialStubDataRule [[FirstRegularPeriodStartDateInitialStubDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
