@startuml

    class FloatingRateFloatingRateMultiplierScheduleDataRule [[FloatingRateFloatingRateMultiplierScheduleDataRule.html]] {
        +validate(FloatingRate): ValidationResult<FloatingRate>
    }

@enduml
