@startuml

    class FloatingRateDefinitionFloatingRateMultiplierDataRule [[FloatingRateDefinitionFloatingRateMultiplierDataRule.html]] {
        +validate(FloatingRateDefinition): ValidationResult<FloatingRateDefinition>
    }

@enduml
