@startuml

    class FutureValueAmountCalculationPeriodNumberOfDaysDataRule [[FutureValueAmountCalculationPeriodNumberOfDaysDataRule.html]] {
        +validate(FutureValueAmount): ValidationResult<FutureValueAmount>
    }

@enduml
