@startuml

    class FutureValueAmountNonNegativeAmountDataRule [[FutureValueAmountNonNegativeAmountDataRule.html]] {
        +validate(FutureValueAmount): ValidationResult<FutureValueAmount>
    }

@enduml
