@startuml

    class IndexReferenceInformationIndexSeriesDataRule [[IndexReferenceInformationIndexSeriesDataRule.html]] {
        +validate(IndexReferenceInformation): ValidationResult<IndexReferenceInformation>
    }

@enduml
