@startuml

    class IndexReferenceInformationIndexAnnexVersionDataRule [[IndexReferenceInformationIndexAnnexVersionDataRule.html]] {
        +validate(IndexReferenceInformation): ValidationResult<IndexReferenceInformation>
    }

@enduml
