@startuml

    class InterestRatePayoutActualQuantityDataRule [[InterestRatePayoutActualQuantityDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
