@startuml

    class InterestRatePayoutFutureValueNotionalDataRule [[InterestRatePayoutFutureValueNotionalDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
