@startuml

    class LastRegularPeriodEndDateFinalStubDataRule [[LastRegularPeriodEndDateFinalStubDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
