@startuml

    class MinimumNumberOfOptionsMinimumNumberOfOptionsDataRule [[MinimumNumberOfOptionsMinimumNumberOfOptionsDataRule.html]] {
        +validate(MultipleExercise): ValidationResult<MultipleExercise>
    }

@enduml
