@startuml

    class MultipleValuationDatesNumberValuationDatesDataRule [[MultipleValuationDatesNumberValuationDatesDataRule.html]] {
        +validate(MultipleValuationDates): ValidationResult<MultipleValuationDates>
    }

@enduml
