@startuml

    class MultipleExerciseMaximumNumberOfOptionsDataRule [[MultipleExerciseMaximumNumberOfOptionsDataRule.html]] {
        +validate(MultipleExercise): ValidationResult<MultipleExercise>
    }

@enduml
