@startuml

    class MultipleValuationDatesBusinessDaysThereafterDataRule [[MultipleValuationDatesBusinessDaysThereafterDataRule.html]] {
        +validate(MultipleValuationDates): ValidationResult<MultipleValuationDates>
    }

@enduml
