@startuml

    class NonNegativeScheduleInitialValueDataRule [[NonNegativeScheduleInitialValueDataRule.html]] {
        +validate(NonNegativeSchedule): ValidationResult<NonNegativeSchedule>
    }

@enduml
