@startuml

    class NotionalStepRuleNotionalStepRateDataRule [[NotionalStepRuleNotionalStepRateDataRule.html]] {
        +validate(NotionalStepRule): ValidationResult<NotionalStepRule>
    }

@enduml
