@startuml

    class NotionalStepRuleNotionalStepAmountDataRule [[NotionalStepRuleNotionalStepAmountDataRule.html]] {
        +validate(NotionalStepRule): ValidationResult<NotionalStepRule>
    }

@enduml
