@startuml

    class OptionDenominationNumberOfOptionsDataRule [[OptionDenominationNumberOfOptionsDataRule.html]] {
        +validate(OptionDenomination): ValidationResult<OptionDenomination>
    }

@enduml
