@startuml

    class OptionSettlementCashSettlementTermsDataRule [[OptionSettlementCashSettlementTermsDataRule.html]] {
        +validate(OptionSettlement): ValidationResult<OptionSettlement>
    }

@enduml
