@startuml

    class OptionSettlementPhysicalSettlementTermsDataRule [[OptionSettlementPhysicalSettlementTermsDataRule.html]] {
        +validate(OptionSettlement): ValidationResult<OptionSettlement>
    }

@enduml
