@startuml

    class OptionDenominationOptionEntitlementDataRule [[OptionDenominationOptionEntitlementDataRule.html]] {
        +validate(OptionDenomination): ValidationResult<OptionDenomination>
    }

@enduml
