@startuml

    class PhysicalSettlementPeriodMaximumBusinessDaysDataRule [[PhysicalSettlementPeriodMaximumBusinessDaysDataRule.html]] {
        +validate(PhysicalSettlementPeriod): ValidationResult<PhysicalSettlementPeriod>
    }

@enduml
