@startuml

    class PhysicalSettlementPeriodBusinessDaysDataRule [[PhysicalSettlementPeriodBusinessDaysDataRule.html]] {
        +validate(PhysicalSettlementPeriod): ValidationResult<PhysicalSettlementPeriod>
    }

@enduml
