@startuml

    class PubliclyAvailableInformationSpecifiedNumberDataRule [[PubliclyAvailableInformationSpecifiedNumberDataRule.html]] {
        +validate(PubliclyAvailableInformation): ValidationResult<PubliclyAvailableInformation>
    }

@enduml
