@startuml

    class SettlementProvisionSettlementCurrencyDataRule [[SettlementProvisionSettlementCurrencyDataRule.html]] {
        +validate(InterestRatePayout): ValidationResult<InterestRatePayout>
    }

@enduml
