@startuml

    class SingleValuationDateBusinessDaysDataRule [[SingleValuationDateBusinessDaysDataRule.html]] {
        +validate(SingleValuationDate): ValidationResult<SingleValuationDate>
    }

@enduml
