@startuml

    class ValuationPostponementMaximumDaysOfPostponementDataRule [[ValuationPostponementMaximumDaysOfPostponementDataRule.html]] {
        +validate(FallbackReferencePrice): ValidationResult<FallbackReferencePrice>
    }

@enduml
