@startuml

    class VanillaSemiAnnualPaymentQuarterlyResetDataRule [[VanillaSemiAnnualPaymentQuarterlyResetDataRule.html]] {
        +validate(EconomicTerms): ValidationResult<EconomicTerms>
    }

@enduml
