@startuml

    class VanillaAnnualPaymentDifferentResetFrequencyDataRule [[VanillaAnnualPaymentDifferentResetFrequencyDataRule.html]] {
        +validate(EconomicTerms): ValidationResult<EconomicTerms>
    }

@enduml
