@startuml

    class VanillaQuarterlyPaymentMonthlyResetDataRule [[VanillaQuarterlyPaymentMonthlyResetDataRule.html]] {
        +validate(EconomicTerms): ValidationResult<EconomicTerms>
    }

@enduml
