@startuml

    class WeightedAveragingObservationObservationNumberDataRule [[WeightedAveragingObservationObservationNumberDataRule.html]] {
        +validate(WeightedAveragingObservation): ValidationResult<WeightedAveragingObservation>
    }

@enduml
