@startuml

    class WeightedAveragingObservationWeightDataRule [[WeightedAveragingObservationWeightDataRule.html]] {
        +validate(WeightedAveragingObservation): ValidationResult<WeightedAveragingObservation>
    }

@enduml
