@startuml

    class CalculationPeriodImpl [[CalculationPeriodImpl.html]] {
        +CalculationPeriodImpl(LocalDate)
        +execute(CalculationPeriodDates): CalculationPeriod.CalculationResult
    }

@enduml
