@startuml

    class DaysInPeriod.CalculationResult [[DaysInPeriod.CalculationResult.html]] {
        +getDays(): Integer
        +setDays(Integer): DaysInPeriod.CalculationResult
        +getAttributes(): List<IResult.Attribute<?>>
    }

@enduml
