@startuml

    class AdditionalFixedPaymentsOnlyExistsValidator [[AdditionalFixedPaymentsOnlyExistsValidator.html]] {
        +validate(AdditionalFixedPayments, String): ValidationResult<AdditionalFixedPayments>
    }

@enduml
