@startuml

    class AdjustableOrAdjustedDateOnlyExistsValidator [[AdjustableOrAdjustedDateOnlyExistsValidator.html]] {
        +validate(AdjustableOrAdjustedDate, String): ValidationResult<AdjustableOrAdjustedDate>
    }

@enduml
