@startuml

    class AdjustableOrRelativeDatesOnlyExistsValidator [[AdjustableOrRelativeDatesOnlyExistsValidator.html]] {
        +validate(AdjustableOrRelativeDates, String): ValidationResult<AdjustableOrRelativeDates>
    }

@enduml
