@startuml

    class AdjustableOrAdjustedOrRelativeDateOnlyExistsValidator [[AdjustableOrAdjustedOrRelativeDateOnlyExistsValidator.html]] {
        +validate(AdjustableOrAdjustedOrRelativeDate, String): ValidationResult<AdjustableOrAdjustedOrRelativeDate>
    }

@enduml
