@startuml

    class AdjustedRelativeDateOffsetOnlyExistsValidator [[AdjustedRelativeDateOffsetOnlyExistsValidator.html]] {
        +validate(AdjustedRelativeDateOffset, String): ValidationResult<AdjustedRelativeDateOffset>
    }

@enduml
