@startuml

    class AdjustableOrRelativeDateOnlyExistsValidator [[AdjustableOrRelativeDateOnlyExistsValidator.html]] {
        +validate(AdjustableOrRelativeDate, String): ValidationResult<AdjustableOrRelativeDate>
    }

@enduml
