@startuml

    class AllocationOutcomeOnlyExistsValidator [[AllocationOutcomeOnlyExistsValidator.html]] {
        +validate(AllocationOutcome, String): ValidationResult<AllocationOutcome>
    }

@enduml
