@startuml

    class AllocationPrimitiveOnlyExistsValidator [[AllocationPrimitiveOnlyExistsValidator.html]] {
        +validate(AllocationPrimitive, String): ValidationResult<AllocationPrimitive>
    }

@enduml
