@startuml

    class AutomaticExerciseOnlyExistsValidator [[AutomaticExerciseOnlyExistsValidator.html]] {
        +validate(AutomaticExercise, String): ValidationResult<AutomaticExercise>
    }

@enduml
