@startuml

    class AveragingScheduleOnlyExistsValidator [[AveragingScheduleOnlyExistsValidator.html]] {
        +validate(AveragingSchedule, String): ValidationResult<AveragingSchedule>
    }

@enduml
