@startuml

    class AveragingObservationListOnlyExistsValidator [[AveragingObservationListOnlyExistsValidator.html]] {
        +validate(AveragingObservationList, String): ValidationResult<AveragingObservationList>
    }

@enduml
