@startuml

    class BasketReferenceInformationOnlyExistsValidator [[BasketReferenceInformationOnlyExistsValidator.html]] {
        +validate(BasketReferenceInformation, String): ValidationResult<BasketReferenceInformation>
    }

@enduml
