@startuml

    class BrokerConfirmationOnlyExistsValidator [[BrokerConfirmationOnlyExistsValidator.html]] {
        +validate(BrokerConfirmation, String): ValidationResult<BrokerConfirmation>
    }

@enduml
