@startuml

    class BusinessDateRangeOnlyExistsValidator [[BusinessDateRangeOnlyExistsValidator.html]] {
        +validate(BusinessDateRange, String): ValidationResult<BusinessDateRange>
    }

@enduml
