@startuml

    class BusinessDayAdjustmentsOnlyExistsValidator [[BusinessDayAdjustmentsOnlyExistsValidator.html]] {
        +validate(BusinessDayAdjustments, String): ValidationResult<BusinessDayAdjustments>
    }

@enduml
