@startuml

    class BusinessCenterTimeOnlyExistsValidator [[BusinessCenterTimeOnlyExistsValidator.html]] {
        +validate(BusinessCenterTime, String): ValidationResult<BusinessCenterTime>
    }

@enduml
