@startuml

    class CalculationPeriodOnlyExistsValidator [[CalculationPeriodOnlyExistsValidator.html]] {
        +validate(CalculationPeriod, String): ValidationResult<CalculationPeriod>
    }

@enduml
