@startuml

    class CalculationAgentModelOnlyExistsValidator [[CalculationAgentModelOnlyExistsValidator.html]] {
        +validate(CalculationAgentModel, String): ValidationResult<CalculationAgentModel>
    }

@enduml
