@startuml

    class CalculationAmountOnlyExistsValidator [[CalculationAmountOnlyExistsValidator.html]] {
        +validate(CalculationAmount, String): ValidationResult<CalculationAmount>
    }

@enduml
