@startuml

    class CalculationPeriodDatesOnlyExistsValidator [[CalculationPeriodDatesOnlyExistsValidator.html]] {
        +validate(CalculationPeriodDates, String): ValidationResult<CalculationPeriodDates>
    }

@enduml
