@startuml

    class CalculationPeriodFrequencyOnlyExistsValidator [[CalculationPeriodFrequencyOnlyExistsValidator.html]] {
        +validate(CalculationPeriodFrequency, String): ValidationResult<CalculationPeriodFrequency>
    }

@enduml
