@startuml

    class CancelableProvisionOnlyExistsValidator [[CancelableProvisionOnlyExistsValidator.html]] {
        +validate(CancelableProvision, String): ValidationResult<CancelableProvision>
    }

@enduml
