@startuml

    class CancelableProvisionAdjustedDatesOnlyExistsValidator [[CancelableProvisionAdjustedDatesOnlyExistsValidator.html]] {
        +validate(CancelableProvisionAdjustedDates, String): ValidationResult<CancelableProvisionAdjustedDates>
    }

@enduml
