@startuml

    class CancellationEventOnlyExistsValidator [[CancellationEventOnlyExistsValidator.html]] {
        +validate(CancellationEvent, String): ValidationResult<CancellationEvent>
    }

@enduml
