@startuml

    class CashSettlementTermsOnlyExistsValidator [[CashSettlementTermsOnlyExistsValidator.html]] {
        +validate(CashSettlementTerms, String): ValidationResult<CashSettlementTerms>
    }

@enduml
