@startuml

    class CashSettlementPaymentDateOnlyExistsValidator [[CashSettlementPaymentDateOnlyExistsValidator.html]] {
        +validate(CashSettlementPaymentDate, String): ValidationResult<CashSettlementPaymentDate>
    }

@enduml
