@startuml

    class CashSettlementReferenceBanksOnlyExistsValidator [[CashSettlementReferenceBanksOnlyExistsValidator.html]] {
        +validate(CashSettlementReferenceBanks, String): ValidationResult<CashSettlementReferenceBanks>
    }

@enduml
