@startuml

    class CashflowRepresentationOnlyExistsValidator [[CashflowRepresentationOnlyExistsValidator.html]] {
        +validate(CashflowRepresentation, String): ValidationResult<CashflowRepresentation>
    }

@enduml
