@startuml

    class ConstituentWeightOnlyExistsValidator [[ConstituentWeightOnlyExistsValidator.html]] {
        +validate(ConstituentWeight, String): ValidationResult<ConstituentWeight>
    }

@enduml
