@startuml

    class ContractOrContractReferenceOnlyExistsValidator [[ContractOrContractReferenceOnlyExistsValidator.html]] {
        +validate(ContractOrContractReference, String): ValidationResult<ContractOrContractReference>
    }

@enduml
