@startuml

    class ContractIdentifierOnlyExistsValidator [[ContractIdentifierOnlyExistsValidator.html]] {
        +validate(ContractIdentifier, String): ValidationResult<ContractIdentifier>
    }

@enduml
