@startuml

    class ContractualQuantityOnlyExistsValidator [[ContractualQuantityOnlyExistsValidator.html]] {
        +validate(ContractualQuantity, String): ValidationResult<ContractualQuantity>
    }

@enduml
