@startuml

    class ContractReferenceOnlyExistsValidator [[ContractReferenceOnlyExistsValidator.html]] {
        +validate(ContractReference, String): ValidationResult<ContractReference>
    }

@enduml
