@startuml

    class ContractualMatrixOnlyExistsValidator [[ContractualMatrixOnlyExistsValidator.html]] {
        +validate(ContractualMatrix, String): ValidationResult<ContractualMatrix>
    }

@enduml
