@startuml

    class ContractualTermsSupplementOnlyExistsValidator [[ContractualTermsSupplementOnlyExistsValidator.html]] {
        +validate(ContractualTermsSupplement, String): ValidationResult<ContractualTermsSupplement>
    }

@enduml
