@startuml

    class ContractualProductOnlyExistsValidator [[ContractualProductOnlyExistsValidator.html]] {
        +validate(ContractualProduct, String): ValidationResult<ContractualProduct>
    }

@enduml
