@startuml

    class ContractIdentifierExtendedOnlyExistsValidator [[ContractIdentifierExtendedOnlyExistsValidator.html]] {
        +validate(ContractIdentifierExtended, String): ValidationResult<ContractIdentifierExtended>
    }

@enduml
