@startuml

    class CreditDefaultPayoutOnlyExistsValidator [[CreditDefaultPayoutOnlyExistsValidator.html]] {
        +validate(CreditDefaultPayout, String): ValidationResult<CreditDefaultPayout>
    }

@enduml
