@startuml

    class CreditSupportAgreementOnlyExistsValidator [[CreditSupportAgreementOnlyExistsValidator.html]] {
        +validate(CreditSupportAgreement, String): ValidationResult<CreditSupportAgreement>
    }

@enduml
