@startuml

    class CreditEventNoticeOnlyExistsValidator [[CreditEventNoticeOnlyExistsValidator.html]] {
        +validate(CreditEventNotice, String): ValidationResult<CreditEventNotice>
    }

@enduml
