@startuml

    class CrossCurrencyTermsOnlyExistsValidator [[CrossCurrencyTermsOnlyExistsValidator.html]] {
        +validate(CrossCurrencyTerms, String): ValidationResult<CrossCurrencyTerms>
    }

@enduml
