@startuml

    class CrossCurrencyMethodOnlyExistsValidator [[CrossCurrencyMethodOnlyExistsValidator.html]] {
        +validate(CrossCurrencyMethod, String): ValidationResult<CrossCurrencyMethod>
    }

@enduml
