@startuml

    class DateRelativeToCalculationPeriodDatesOnlyExistsValidator [[DateRelativeToCalculationPeriodDatesOnlyExistsValidator.html]] {
        +validate(DateRelativeToCalculationPeriodDates, String): ValidationResult<DateRelativeToCalculationPeriodDates>
    }

@enduml
