@startuml

    class DateRelativeToPaymentDatesOnlyExistsValidator [[DateRelativeToPaymentDatesOnlyExistsValidator.html]] {
        +validate(DateRelativeToPaymentDates, String): ValidationResult<DateRelativeToPaymentDates>
    }

@enduml
