@startuml

    class DeliverableObligationsOnlyExistsValidator [[DeliverableObligationsOnlyExistsValidator.html]] {
        +validate(DeliverableObligations, String): ValidationResult<DeliverableObligations>
    }

@enduml
