@startuml

    class EarlyTerminationEventOnlyExistsValidator [[EarlyTerminationEventOnlyExistsValidator.html]] {
        +validate(EarlyTerminationEvent, String): ValidationResult<EarlyTerminationEvent>
    }

@enduml
