@startuml

    class EarlyTerminationProvisionOnlyExistsValidator [[EarlyTerminationProvisionOnlyExistsValidator.html]] {
        +validate(EarlyTerminationProvision, String): ValidationResult<EarlyTerminationProvision>
    }

@enduml
