@startuml

    class ExecutionReferenceOnlyExistsValidator [[ExecutionReferenceOnlyExistsValidator.html]] {
        +validate(ExecutionReference, String): ValidationResult<ExecutionReference>
    }

@enduml
