@startuml

    class ExercisePrimitiveOnlyExistsValidator [[ExercisePrimitiveOnlyExistsValidator.html]] {
        +validate(ExercisePrimitive, String): ValidationResult<ExercisePrimitive>
    }

@enduml
