@startuml

    class ExerciseFeeScheduleOnlyExistsValidator [[ExerciseFeeScheduleOnlyExistsValidator.html]] {
        +validate(ExerciseFeeSchedule, String): ValidationResult<ExerciseFeeSchedule>
    }

@enduml
