@startuml

    class ExerciseProcedureOnlyExistsValidator [[ExerciseProcedureOnlyExistsValidator.html]] {
        +validate(ExerciseProcedure, String): ValidationResult<ExerciseProcedure>
    }

@enduml
