@startuml

    class ExtendibleProvisionOnlyExistsValidator [[ExtendibleProvisionOnlyExistsValidator.html]] {
        +validate(ExtendibleProvision, String): ValidationResult<ExtendibleProvision>
    }

@enduml
