@startuml

    class ExtendibleProvisionAdjustedDatesOnlyExistsValidator [[ExtendibleProvisionAdjustedDatesOnlyExistsValidator.html]] {
        +validate(ExtendibleProvisionAdjustedDates, String): ValidationResult<ExtendibleProvisionAdjustedDates>
    }

@enduml
