@startuml

    class FallbackReferencePriceOnlyExistsValidator [[FallbackReferencePriceOnlyExistsValidator.html]] {
        +validate(FallbackReferencePrice, String): ValidationResult<FallbackReferencePrice>
    }

@enduml
