@startuml

    class FinalCalculationPeriodDateAdjustmentOnlyExistsValidator [[FinalCalculationPeriodDateAdjustmentOnlyExistsValidator.html]] {
        +validate(FinalCalculationPeriodDateAdjustment, String): ValidationResult<FinalCalculationPeriodDateAdjustment>
    }

@enduml
