@startuml

    class FixedIncomeSecurityOnlyExistsValidator [[FixedIncomeSecurityOnlyExistsValidator.html]] {
        +validate(FixedIncomeSecurity, String): ValidationResult<FixedIncomeSecurity>
    }

@enduml
