@startuml

    class FloatingRateCalculationOnlyExistsValidator [[FloatingRateCalculationOnlyExistsValidator.html]] {
        +validate(FloatingRateCalculation, String): ValidationResult<FloatingRateCalculation>
    }

@enduml
