@startuml

    class FloatingRateDefinitionOnlyExistsValidator [[FloatingRateDefinitionOnlyExistsValidator.html]] {
        +validate(FloatingRateDefinition, String): ValidationResult<FloatingRateDefinition>
    }

@enduml
