@startuml

    class FloatingAmountProvisionsOnlyExistsValidator [[FloatingAmountProvisionsOnlyExistsValidator.html]] {
        +validate(FloatingAmountProvisions, String): ValidationResult<FloatingAmountProvisions>
    }

@enduml
