@startuml

    class FloatingAmountEventsOnlyExistsValidator [[FloatingAmountEventsOnlyExistsValidator.html]] {
        +validate(FloatingAmountEvents, String): ValidationResult<FloatingAmountEvents>
    }

@enduml
