@startuml

    class FutureValueAmountOnlyExistsValidator [[FutureValueAmountOnlyExistsValidator.html]] {
        +validate(FutureValueAmount, String): ValidationResult<FutureValueAmount>
    }

@enduml
