@startuml

    class FxLinkedNotionalScheduleOnlyExistsValidator [[FxLinkedNotionalScheduleOnlyExistsValidator.html]] {
        +validate(FxLinkedNotionalSchedule, String): ValidationResult<FxLinkedNotionalSchedule>
    }

@enduml
