@startuml

    class FxLinkedNotionalAmountOnlyExistsValidator [[FxLinkedNotionalAmountOnlyExistsValidator.html]] {
        +validate(FxLinkedNotionalAmount, String): ValidationResult<FxLinkedNotionalAmount>
    }

@enduml
