@startuml

    class GracePeriodExtensionOnlyExistsValidator [[GracePeriodExtensionOnlyExistsValidator.html]] {
        +validate(GracePeriodExtension, String): ValidationResult<GracePeriodExtension>
    }

@enduml
