@startuml

    class IndexReferenceInformationOnlyExistsValidator [[IndexReferenceInformationOnlyExistsValidator.html]] {
        +validate(IndexReferenceInformation, String): ValidationResult<IndexReferenceInformation>
    }

@enduml
