@startuml

    class IndependentAmountOnlyExistsValidator [[IndependentAmountOnlyExistsValidator.html]] {
        +validate(IndependentAmount, String): ValidationResult<IndependentAmount>
    }

@enduml
