@startuml

    class InflationRateCalculationOnlyExistsValidator [[InflationRateCalculationOnlyExistsValidator.html]] {
        +validate(InflationRateCalculation, String): ValidationResult<InflationRateCalculation>
    }

@enduml
