@startuml

    class InformationSourceOnlyExistsValidator [[InformationSourceOnlyExistsValidator.html]] {
        +validate(InformationSource, String): ValidationResult<InformationSource>
    }

@enduml
