@startuml

    class InitialFixingDateOnlyExistsValidator [[InitialFixingDateOnlyExistsValidator.html]] {
        +validate(InitialFixingDate, String): ValidationResult<InitialFixingDate>
    }

@enduml
