@startuml

    class InterestShortFallOnlyExistsValidator [[InterestShortFallOnlyExistsValidator.html]] {
        +validate(InterestShortFall, String): ValidationResult<InterestShortFall>
    }

@enduml
