@startuml

    class InterestRateCurveOnlyExistsValidator [[InterestRateCurveOnlyExistsValidator.html]] {
        +validate(InterestRateCurve, String): ValidationResult<InterestRateCurve>
    }

@enduml
