@startuml

    class InterestRatePayoutOnlyExistsValidator [[InterestRatePayoutOnlyExistsValidator.html]] {
        +validate(InterestRatePayout, String): ValidationResult<InterestRatePayout>
    }

@enduml
