@startuml

    class LoanParticipationOnlyExistsValidator [[LoanParticipationOnlyExistsValidator.html]] {
        +validate(LoanParticipation, String): ValidationResult<LoanParticipation>
    }

@enduml
