@startuml

    class MandatoryEarlyTerminationOnlyExistsValidator [[MandatoryEarlyTerminationOnlyExistsValidator.html]] {
        +validate(MandatoryEarlyTermination, String): ValidationResult<MandatoryEarlyTermination>
    }

@enduml
