@startuml

    class MandatoryEarlyTerminationAdjustedDatesOnlyExistsValidator [[MandatoryEarlyTerminationAdjustedDatesOnlyExistsValidator.html]] {
        +validate(MandatoryEarlyTerminationAdjustedDates, String): ValidationResult<MandatoryEarlyTerminationAdjustedDates>
    }

@enduml
