@startuml

    class MasterConfirmationOnlyExistsValidator [[MasterConfirmationOnlyExistsValidator.html]] {
        +validate(MasterConfirmation, String): ValidationResult<MasterConfirmation>
    }

@enduml
