@startuml

    class MessageInformationOnlyExistsValidator [[MessageInformationOnlyExistsValidator.html]] {
        +validate(MessageInformation, String): ValidationResult<MessageInformation>
    }

@enduml
