@startuml

    class MultipleValuationDatesOnlyExistsValidator [[MultipleValuationDatesOnlyExistsValidator.html]] {
        +validate(MultipleValuationDates, String): ValidationResult<MultipleValuationDates>
    }

@enduml
