@startuml

    class NaturalPersonRoleOnlyExistsValidator [[NaturalPersonRoleOnlyExistsValidator.html]] {
        +validate(NaturalPersonRole, String): ValidationResult<NaturalPersonRole>
    }

@enduml
