@startuml

    class NewTradePrimitiveOnlyExistsValidator [[NewTradePrimitiveOnlyExistsValidator.html]] {
        +validate(NewTradePrimitive, String): ValidationResult<NewTradePrimitive>
    }

@enduml
