@startuml

    class NonDeliverableSettlementOnlyExistsValidator [[NonDeliverableSettlementOnlyExistsValidator.html]] {
        +validate(NonDeliverableSettlement, String): ValidationResult<NonDeliverableSettlement>
    }

@enduml
