@startuml

    class NonNegativeAmountScheduleOnlyExistsValidator [[NonNegativeAmountScheduleOnlyExistsValidator.html]] {
        +validate(NonNegativeAmountSchedule, String): ValidationResult<NonNegativeAmountSchedule>
    }

@enduml
