@startuml

    class NonNegativeScheduleOnlyExistsValidator [[NonNegativeScheduleOnlyExistsValidator.html]] {
        +validate(NonNegativeSchedule, String): ValidationResult<NonNegativeSchedule>
    }

@enduml
