@startuml

    class NotDomesticCurrencyOnlyExistsValidator [[NotDomesticCurrencyOnlyExistsValidator.html]] {
        +validate(NotDomesticCurrency, String): ValidationResult<NotDomesticCurrency>
    }

@enduml
