@startuml

    class ObservationSourceOnlyExistsValidator [[ObservationSourceOnlyExistsValidator.html]] {
        +validate(ObservationSource, String): ValidationResult<ObservationSource>
    }

@enduml
