@startuml

    class ObservationPrimitiveOnlyExistsValidator [[ObservationPrimitiveOnlyExistsValidator.html]] {
        +validate(ObservationPrimitive, String): ValidationResult<ObservationPrimitive>
    }

@enduml
