@startuml

    class OptionalEarlyTerminationAdjustedDatesOnlyExistsValidator [[OptionalEarlyTerminationAdjustedDatesOnlyExistsValidator.html]] {
        +validate(OptionalEarlyTerminationAdjustedDates, String): ValidationResult<OptionalEarlyTerminationAdjustedDates>
    }

@enduml
