@startuml

    class OptionalEarlyTerminationOnlyExistsValidator [[OptionalEarlyTerminationOnlyExistsValidator.html]] {
        +validate(OptionalEarlyTermination, String): ValidationResult<OptionalEarlyTermination>
    }

@enduml
