@startuml

    class OptionPhysicalSettlementOnlyExistsValidator [[OptionPhysicalSettlementOnlyExistsValidator.html]] {
        +validate(OptionPhysicalSettlement, String): ValidationResult<OptionPhysicalSettlement>
    }

@enduml
