@startuml

    class OptionCashSettlementOnlyExistsValidator [[OptionCashSettlementOnlyExistsValidator.html]] {
        +validate(OptionCashSettlement, String): ValidationResult<OptionCashSettlement>
    }

@enduml
