@startuml

    class OptionDenominationOnlyExistsValidator [[OptionDenominationOnlyExistsValidator.html]] {
        +validate(OptionDenomination, String): ValidationResult<OptionDenomination>
    }

@enduml
