@startuml

    class PackageInformationOnlyExistsValidator [[PackageInformationOnlyExistsValidator.html]] {
        +validate(PackageInformation, String): ValidationResult<PackageInformation>
    }

@enduml
