@startuml

    class PartyAndAccountReferenceOnlyExistsValidator [[PartyAndAccountReferenceOnlyExistsValidator.html]] {
        +validate(PartyAndAccountReference, String): ValidationResult<PartyAndAccountReference>
    }

@enduml
