@startuml

    class PartyContractInformationOnlyExistsValidator [[PartyContractInformationOnlyExistsValidator.html]] {
        +validate(PartyContractInformation, String): ValidationResult<PartyContractInformation>
    }

@enduml
