@startuml

    class PartyContractIdentifierOnlyExistsValidator [[PartyContractIdentifierOnlyExistsValidator.html]] {
        +validate(PartyContractIdentifier, String): ValidationResult<PartyContractIdentifier>
    }

@enduml
