@startuml

    class PaymentCalculationPeriodOnlyExistsValidator [[PaymentCalculationPeriodOnlyExistsValidator.html]] {
        +validate(PaymentCalculationPeriod, String): ValidationResult<PaymentCalculationPeriod>
    }

@enduml
