@startuml

    class PaymentDiscountingOnlyExistsValidator [[PaymentDiscountingOnlyExistsValidator.html]] {
        +validate(PaymentDiscounting, String): ValidationResult<PaymentDiscounting>
    }

@enduml
