@startuml

    class PCDeliverableObligationCharacOnlyExistsValidator [[PCDeliverableObligationCharacOnlyExistsValidator.html]] {
        +validate(PCDeliverableObligationCharac, String): ValidationResult<PCDeliverableObligationCharac>
    }

@enduml
