@startuml

    class PhysicalSettlementPeriodOnlyExistsValidator [[PhysicalSettlementPeriodOnlyExistsValidator.html]] {
        +validate(PhysicalSettlementPeriod, String): ValidationResult<PhysicalSettlementPeriod>
    }

@enduml
