@startuml

    class PhysicalSettlementTermsOnlyExistsValidator [[PhysicalSettlementTermsOnlyExistsValidator.html]] {
        +validate(PhysicalSettlementTerms, String): ValidationResult<PhysicalSettlementTerms>
    }

@enduml
