@startuml

    class PremiumExpressionOnlyExistsValidator [[PremiumExpressionOnlyExistsValidator.html]] {
        +validate(PremiumExpression, String): ValidationResult<PremiumExpression>
    }

@enduml
