@startuml

    class PriceSourceDisruptionOnlyExistsValidator [[PriceSourceDisruptionOnlyExistsValidator.html]] {
        +validate(PriceSourceDisruption, String): ValidationResult<PriceSourceDisruption>
    }

@enduml
