@startuml

    class PrincipalExchangeOnlyExistsValidator [[PrincipalExchangeOnlyExistsValidator.html]] {
        +validate(PrincipalExchange, String): ValidationResult<PrincipalExchange>
    }

@enduml
