@startuml

    class PrincipalExchangesOnlyExistsValidator [[PrincipalExchangesOnlyExistsValidator.html]] {
        +validate(PrincipalExchanges, String): ValidationResult<PrincipalExchanges>
    }

@enduml
