@startuml

    class PriorDateInstanceOnlyExistsValidator [[PriorDateInstanceOnlyExistsValidator.html]] {
        +validate(PriorDateInstance, String): ValidationResult<PriorDateInstance>
    }

@enduml
