@startuml

    class ProductIdentificationOnlyExistsValidator [[ProductIdentificationOnlyExistsValidator.html]] {
        +validate(ProductIdentification, String): ValidationResult<ProductIdentification>
    }

@enduml
