@startuml

    class ProductIdentifierOnlyExistsValidator [[ProductIdentifierOnlyExistsValidator.html]] {
        +validate(ProductIdentifier, String): ValidationResult<ProductIdentifier>
    }

@enduml
