@startuml

    class PubliclyAvailableInformationOnlyExistsValidator [[PubliclyAvailableInformationOnlyExistsValidator.html]] {
        +validate(PubliclyAvailableInformation, String): ValidationResult<PubliclyAvailableInformation>
    }

@enduml
