@startuml

    class QuantityChangePrimitiveOnlyExistsValidator [[QuantityChangePrimitiveOnlyExistsValidator.html]] {
        +validate(QuantityChangePrimitive, String): ValidationResult<QuantityChangePrimitive>
    }

@enduml
