@startuml

    class QuotedCurrencyPairOnlyExistsValidator [[QuotedCurrencyPairOnlyExistsValidator.html]] {
        +validate(QuotedCurrencyPair, String): ValidationResult<QuotedCurrencyPair>
    }

@enduml
