@startuml

    class ReferenceInformationOnlyExistsValidator [[ReferenceInformationOnlyExistsValidator.html]] {
        +validate(ReferenceInformation, String): ValidationResult<ReferenceInformation>
    }

@enduml
