@startuml

    class ReferenceSwapCurveOnlyExistsValidator [[ReferenceSwapCurveOnlyExistsValidator.html]] {
        +validate(ReferenceSwapCurve, String): ValidationResult<ReferenceSwapCurve>
    }

@enduml
