@startuml

    class ReferencePoolItemOnlyExistsValidator [[ReferencePoolItemOnlyExistsValidator.html]] {
        +validate(ReferencePoolItem, String): ValidationResult<ReferencePoolItem>
    }

@enduml
