@startuml

    class ReferenceObligationOnlyExistsValidator [[ReferenceObligationOnlyExistsValidator.html]] {
        +validate(ReferenceObligation, String): ValidationResult<ReferenceObligation>
    }

@enduml
