@startuml

    class RelativeDateOffsetOnlyExistsValidator [[RelativeDateOffsetOnlyExistsValidator.html]] {
        +validate(RelativeDateOffset, String): ValidationResult<RelativeDateOffset>
    }

@enduml
