@startuml

    class SettlementRateSourceOnlyExistsValidator [[SettlementRateSourceOnlyExistsValidator.html]] {
        +validate(SettlementRateSource, String): ValidationResult<SettlementRateSource>
    }

@enduml
