@startuml

    class SettlementProvisionOnlyExistsValidator [[SettlementProvisionOnlyExistsValidator.html]] {
        +validate(SettlementProvision, String): ValidationResult<SettlementProvision>
    }

@enduml
