@startuml

    class SettledEntityMatrixOnlyExistsValidator [[SettledEntityMatrixOnlyExistsValidator.html]] {
        +validate(SettledEntityMatrix, String): ValidationResult<SettledEntityMatrix>
    }

@enduml
