@startuml

    class SingleValuationDateOnlyExistsValidator [[SingleValuationDateOnlyExistsValidator.html]] {
        +validate(SingleValuationDate, String): ValidationResult<SingleValuationDate>
    }

@enduml
