@startuml

    class SpecifiedCurrencyOnlyExistsValidator [[SpecifiedCurrencyOnlyExistsValidator.html]] {
        +validate(SpecifiedCurrency, String): ValidationResult<SpecifiedCurrency>
    }

@enduml
