@startuml

    class StubCalculationPeriodAmountOnlyExistsValidator [[StubCalculationPeriodAmountOnlyExistsValidator.html]] {
        +validate(StubCalculationPeriodAmount, String): ValidationResult<StubCalculationPeriodAmount>
    }

@enduml
