@startuml

    class SwapCurveValuationOnlyExistsValidator [[SwapCurveValuationOnlyExistsValidator.html]] {
        +validate(SwapCurveValuation, String): ValidationResult<SwapCurveValuation>
    }

@enduml
