@startuml

    class TermsChangePrimitiveOnlyExistsValidator [[TermsChangePrimitiveOnlyExistsValidator.html]] {
        +validate(TermsChangePrimitive, String): ValidationResult<TermsChangePrimitive>
    }

@enduml
