@startuml

    class TransferorTransfereeOnlyExistsValidator [[TransferorTransfereeOnlyExistsValidator.html]] {
        +validate(TransferorTransferee, String): ValidationResult<TransferorTransferee>
    }

@enduml
