@startuml

    class ValuationPostponementOnlyExistsValidator [[ValuationPostponementOnlyExistsValidator.html]] {
        +validate(ValuationPostponement, String): ValidationResult<ValuationPostponement>
    }

@enduml
