@startuml

    class WeightedAveragingObservationOnlyExistsValidator [[WeightedAveragingObservationOnlyExistsValidator.html]] {
        +validate(WeightedAveragingObservation, String): ValidationResult<WeightedAveragingObservation>
    }

@enduml
