@startuml

    class DayCountFractionEnum._30_360._Input [[DayCountFractionEnum._30_360._Input.html]] {
        +create(InterestRatePayout, CalculationPeriod): DayCountFractionEnum._30_360._Input
    }

@enduml
