@startuml

    class DayCountFractionEnum.ACT_365_FIXED._Input [[DayCountFractionEnum.ACT_365_FIXED._Input.html]] {
        +create(InterestRatePayout, DaysInPeriod): DayCountFractionEnum.ACT_365_FIXED._Input
    }

@enduml
