@startuml

    class DayCountFractionEnum [[DayCountFractionEnum.html]] {
        +DayCountFractionEnum(DaysInPeriod, CalculationPeriod)
        +calculate(InterestRatePayout, DayCountFractionEnum): BigDecimal
    }

@enduml
