@startuml

    class CancelableProvisionAdjustedDatesMeta [[CancelableProvisionAdjustedDatesMeta.html]] {
        +dataRules(): List<Validator<CancelableProvisionAdjustedDates>>
        +choiceRuleValidators(): List<Validator<CancelableProvisionAdjustedDates>>
        +getOutMappings(): Multimap<String, OutMapping<CancelableProvisionAdjustedDates, ?>>
        +getQualifyFunctions(): List<Function<CancelableProvisionAdjustedDates, QualifyResult>>
        +validator(): Validator<CancelableProvisionAdjustedDates>
        +onlyExistsValidator(): ValidatorWithArg<CancelableProvisionAdjustedDates, String>
    }

@enduml
