@startuml

    class ContractIdentifierMeta [[ContractIdentifierMeta.html]] {
        +dataRules(): List<Validator<ContractIdentifier>>
        +choiceRuleValidators(): List<Validator<ContractIdentifier>>
        +getOutMappings(): Multimap<String, OutMapping<ContractIdentifier, ?>>
        +getQualifyFunctions(): List<Function<ContractIdentifier, QualifyResult>>
        +validator(): Validator<ContractIdentifier>
        +onlyExistsValidator(): ValidatorWithArg<ContractIdentifier, String>
    }

@enduml
