@startuml

    class InceptionMeta [[InceptionMeta.html]] {
        +dataRules(): List<Validator<Inception>>
        +choiceRuleValidators(): List<Validator<Inception>>
        +getOutMappings(): Multimap<String, OutMapping<Inception, ?>>
        +getQualifyFunctions(): List<Function<Inception, QualifyResult>>
        +validator(): Validator<Inception>
        +onlyExistsValidator(): ValidatorWithArg<Inception, String>
    }

@enduml
