@startuml

    class MultipleValuationDatesMeta [[MultipleValuationDatesMeta.html]] {
        +dataRules(): List<Validator<MultipleValuationDates>>
        +choiceRuleValidators(): List<Validator<MultipleValuationDates>>
        +getOutMappings(): Multimap<String, OutMapping<MultipleValuationDates, ?>>
        +getQualifyFunctions(): List<Function<MultipleValuationDates, QualifyResult>>
        +validator(): Validator<MultipleValuationDates>
        +onlyExistsValidator(): ValidatorWithArg<MultipleValuationDates, String>
    }

@enduml
