@startuml

    class NonNegativeStepMeta [[NonNegativeStepMeta.html]] {
        +dataRules(): List<Validator<NonNegativeStep>>
        +choiceRuleValidators(): List<Validator<NonNegativeStep>>
        +getOutMappings(): Multimap<String, OutMapping<NonNegativeStep, ?>>
        +getQualifyFunctions(): List<Function<NonNegativeStep, QualifyResult>>
        +validator(): Validator<NonNegativeStep>
        +onlyExistsValidator(): ValidatorWithArg<NonNegativeStep, String>
    }

@enduml
