@startuml

    class NotionalStepRuleMeta [[NotionalStepRuleMeta.html]] {
        +dataRules(): List<Validator<NotionalStepRule>>
        +choiceRuleValidators(): List<Validator<NotionalStepRule>>
        +getOutMappings(): Multimap<String, OutMapping<NotionalStepRule, ?>>
        +getQualifyFunctions(): List<Function<NotionalStepRule, QualifyResult>>
        +validator(): Validator<NotionalStepRule>
        +onlyExistsValidator(): ValidatorWithArg<NotionalStepRule, String>
    }

@enduml
