@startuml

    class OptionalEarlyTerminationAdjustedDatesMeta [[OptionalEarlyTerminationAdjustedDatesMeta.html]] {
        +dataRules(): List<Validator<OptionalEarlyTerminationAdjustedDates>>
        +choiceRuleValidators(): List<Validator<OptionalEarlyTerminationAdjustedDates>>
        +getOutMappings(): Multimap<String, OutMapping<OptionalEarlyTerminationAdjustedDates, ?>>
        +getQualifyFunctions(): List<Function<OptionalEarlyTerminationAdjustedDates, QualifyResult>>
        +validator(): Validator<OptionalEarlyTerminationAdjustedDates>
        +onlyExistsValidator(): ValidatorWithArg<OptionalEarlyTerminationAdjustedDates, String>
    }

@enduml
