@startuml

    class PriceSourceDisruptionMeta [[PriceSourceDisruptionMeta.html]] {
        +dataRules(): List<Validator<PriceSourceDisruption>>
        +choiceRuleValidators(): List<Validator<PriceSourceDisruption>>
        +getOutMappings(): Multimap<String, OutMapping<PriceSourceDisruption, ?>>
        +getQualifyFunctions(): List<Function<PriceSourceDisruption, QualifyResult>>
        +validator(): Validator<PriceSourceDisruption>
        +onlyExistsValidator(): ValidatorWithArg<PriceSourceDisruption, String>
    }

@enduml
