@startuml

    class RelativeDateOffsetMeta [[RelativeDateOffsetMeta.html]] {
        +dataRules(): List<Validator<RelativeDateOffset>>
        +choiceRuleValidators(): List<Validator<RelativeDateOffset>>
        +getOutMappings(): Multimap<String, OutMapping<RelativeDateOffset, ?>>
        +getQualifyFunctions(): List<Function<RelativeDateOffset, QualifyResult>>
        +validator(): Validator<RelativeDateOffset>
        +onlyExistsValidator(): ValidatorWithArg<RelativeDateOffset, String>
    }

@enduml
