@startuml

    class RelativeDatesMeta [[RelativeDatesMeta.html]] {
        +dataRules(): List<Validator<RelativeDates>>
        +choiceRuleValidators(): List<Validator<RelativeDates>>
        +getOutMappings(): Multimap<String, OutMapping<RelativeDates, ?>>
        +getQualifyFunctions(): List<Function<RelativeDates, QualifyResult>>
        +validator(): Validator<RelativeDates>
        +onlyExistsValidator(): ValidatorWithArg<RelativeDates, String>
    }

@enduml
