@startuml

    class SingleValuationDateMeta [[SingleValuationDateMeta.html]] {
        +dataRules(): List<Validator<SingleValuationDate>>
        +choiceRuleValidators(): List<Validator<SingleValuationDate>>
        +getOutMappings(): Multimap<String, OutMapping<SingleValuationDate, ?>>
        +getQualifyFunctions(): List<Function<SingleValuationDate, QualifyResult>>
        +validator(): Validator<SingleValuationDate>
        +onlyExistsValidator(): ValidatorWithArg<SingleValuationDate, String>
    }

@enduml
