@startuml

    class StrikeScheduleMeta [[StrikeScheduleMeta.html]] {
        +dataRules(): List<Validator<StrikeSchedule>>
        +choiceRuleValidators(): List<Validator<StrikeSchedule>>
        +getOutMappings(): Multimap<String, OutMapping<StrikeSchedule, ?>>
        +getQualifyFunctions(): List<Function<StrikeSchedule, QualifyResult>>
        +validator(): Validator<StrikeSchedule>
        +onlyExistsValidator(): ValidatorWithArg<StrikeSchedule, String>
    }

@enduml
