@startuml

    class ValuationDateMeta [[ValuationDateMeta.html]] {
        +dataRules(): List<Validator<ValuationDate>>
        +choiceRuleValidators(): List<Validator<ValuationDate>>
        +getOutMappings(): Multimap<String, OutMapping<ValuationDate, ?>>
        +getQualifyFunctions(): List<Function<ValuationDate, QualifyResult>>
        +validator(): Validator<ValuationDate>
        +onlyExistsValidator(): ValidatorWithArg<ValuationDate, String>
    }

@enduml
