@startuml

    class AdjustableOrRelativeDateChoiceRule [[AdjustableOrRelativeDateChoiceRule.html]] {
        +validate(AdjustableOrRelativeDate): ValidationResult<AdjustableOrRelativeDate>
    }

@enduml
