@startuml

    class AdjustableOrRelativeDatesChoiceRule [[AdjustableOrRelativeDatesChoiceRule.html]] {
        +validate(AdjustableOrRelativeDates): ValidationResult<AdjustableOrRelativeDates>
    }

@enduml
