@startuml

    class BasketReferenceInformationChoiceRule [[BasketReferenceInformationChoiceRule.html]] {
        +validate(BasketReferenceInformation): ValidationResult<BasketReferenceInformation>
    }

@enduml
