@startuml

    class CashSettlementPaymentDateChoiceRule [[CashSettlementPaymentDateChoiceRule.html]] {
        +validate(CashSettlementPaymentDate): ValidationResult<CashSettlementPaymentDate>
    }

@enduml
