@startuml

    class NonDeliverableSettlementChoiceRule [[NonDeliverableSettlementChoiceRule.html]] {
        +validate(NonDeliverableSettlement): ValidationResult<NonDeliverableSettlement>
    }

@enduml
