@startuml

    class OptionalEarlyTerminationChoiceRule [[OptionalEarlyTerminationChoiceRule.html]] {
        +validate(OptionalEarlyTermination): ValidationResult<OptionalEarlyTermination>
    }

@enduml
