@startuml

    class PartyContractIdentifierChoiceRule [[PartyContractIdentifierChoiceRule.html]] {
        +validate(PartyContractIdentifier): ValidationResult<PartyContractIdentifier>
    }

@enduml
