@startuml

    class PaymentCalculationPeriodChoiceRule [[PaymentCalculationPeriodChoiceRule.html]] {
        +validate(PaymentCalculationPeriod): ValidationResult<PaymentCalculationPeriod>
    }

@enduml
