@startuml

    class PubliclyAvailableInformationChoiceRule [[PubliclyAvailableInformationChoiceRule.html]] {
        +validate(PubliclyAvailableInformation): ValidationResult<PubliclyAvailableInformation>
    }

@enduml
