@startuml

    class WeightedAveragingObservationChoiceRule [[WeightedAveragingObservationChoiceRule.html]] {
        +validate(WeightedAveragingObservation): ValidationResult<WeightedAveragingObservation>
    }

@enduml
